export const CATEGORIES = [
  'Fruits',
  'Movies',
  'Animals',
  'Colors',
  'Instruments',
  'Cartoon Characters',
  'Historical Figures',
  'Sports',
  'Board Games',
  'Vegetables',
  'Musical Genres',
  'Superheroes',
  'Breakfast Foods',
  'Car Brands',
  'Video Games',
  'Desserts',
  'Clothing Items',
  'Snacks',
  'School Subjects',
  'Famous Landmarks',
  'Artists',
  'Spices',
  'TV Shows',
  'Actors',
  'Types of Trees',
  'Currencies',
  'Types of Birds',
  'Languages',
  'Currencies',
  'Shapes',
  'Dog Breeds',
  'Comedians',
  'Ice Cream Flavors',
  'Types of Cheese',
  'Types of Fish',
  'Cartoon Villains',
  'Types of Pasta',
  'Book Genres',
  'Types of Tea',
  'Candy Bars',
  'Types of Soup',
  'Phone Apps',
  'Shoes Brands',
  'Alcholic Drinks',
  'Potato Based Snacks',
  'Sitcoms',
  'Actresses',
  'Universities',
  'Winter Activities',
  'Water Activities',
  'Types of Chocolates',
  'Girls Names',
  'Boys Names',
  'Things That Are Round'
]
